/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wj_record_AudioRecorder */

#ifndef INCLUDE_NATIVE_AUDIO
#define INCLUDE_NATIVE_AUDIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wj_record_AudioRecorder
 * Method:    startRecord
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL startRecord
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     com_wj_record_AudioRecorder
 * Method:    stopRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL stopRecord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
